blueprint:
  name: IKEA ALPSTUGA E2495 Air Quality Sensor (Matter) v1.0
  description: 'Pro-grade automation for the IKEA ALPSTUGA E2495 Matter Air Quality sensor. 
    Allows triggering actions (Air Purifiers, Ventilation, HVAC) based on thresholds for 
    CO2, PM2.5, Air Quality Index (summary state), Temperature, and Humidity.
    '
  domain: automation
  source_url: https://github.com/aledziko/HA-blueprints/blob/main/IKEA/Matter/ikea-alpstuga-e2495/ikea-alpstuga-e2495-matter-air-quality-sensor.yaml
  author: aledziko
  input:
    # Global Settings
    stabilization_time:
      name: Action Trigger Stabilization Time
      description: >
        **Prevent Action Repetition**: This setting ensures the sensor must stay in the new state for X seconds before triggering any action.
        It filters out brief fluctuations and connection drops (unavailable) that would otherwise cause the same action to run multiple times.
        Recommended: 15-60 seconds.
      default: 0
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: "sec"

    # CO2 Settings
    co2_sensor:
      name: CO2 Sensor
      description: Select the CO2 sensor entity (numeric).
      default: []
      selector:
        entity:
          filter:
            - device_class: carbon_dioxide
    co2_high_threshold:
      name: CO2 High Threshold
      description: Trigger when CO2 goes ABOVE this value (ppm).
      default: 1000
      selector:
        number:
          min: 400
          max: 5000
          unit_of_measurement: "ppm"
    action_co2_high:
      name: "Action: CO2 High"
      description: Run when CO2 is high (e.g., open window / ventilation).
      default: []
      selector:
        action: {}
    co2_low_threshold:
      name: CO2 Low Threshold
      description: Trigger when CO2 goes BELOW this value (ppm).
      default: 800
      selector:
        number:
          min: 400
          max: 5000
          unit_of_measurement: "ppm"
    action_co2_low:
      name: "Action: CO2 Low"
      description: Run when CO2 is low (e.g., stop ventilation).
      default: []
      selector:
        action: {}

    # Particulate Matter (PM2.5) Settings
    pm25_sensor:
      name: PM2.5 Sensor
      description: Select the PM2.5 sensor entity (numeric).
      default: []
      selector:
        entity:
          filter:
            - device_class: pm25
    pm25_high_threshold:
      name: PM2.5 High Threshold
      description: Trigger when PM2.5 goes ABOVE this value (µg/m³).
      default: 25
      selector:
        number:
          min: 0
          max: 500
          unit_of_measurement: "µg/m³"
    action_pm25_high:
      name: "Action: PM2.5 High"
      description: Run when PM2.5 is high (e.g., turn on Air Purifier).
      default: []
      selector:
        action: {}
    pm25_low_threshold:
      name: PM2.5 Low Threshold
      description: Trigger when PM2.5 goes BELOW this value (µg/m³).
      default: 10
      selector:
        number:
          min: 0
          max: 500
          unit_of_measurement: "µg/m³"
    action_pm25_low:
      name: "Action: PM2.5 Low"
      description: Run when PM2.5 is low (e.g., stop Air Purifier).
      default: []
      selector:
        action: {}

    # Air Quality Index (AQI) Settings
    aqi_sensor:
      name: Air Quality Summary Sensor
      description: Select the general "Air Quality" sensor entity (string-based).
      default: []
      selector:
        entity:
          filter:
            - device_class: enum
              integration: matter
    aqi_trigger_states:
      name: Air Quality Alert States
      description: Action runs when the sensor switches to any of these "warning" states.
      default:
        - "poor"
        - "very_poor"
        - "extremely_poor"
        - "moderate"
      selector:
        select:
          multiple: true
          options:
            - "good"
            - "fair"
            - "moderate"
            - "poor"
            - "very_poor"
            - "extremely_poor"
            - "unknown"
    action_aqi_high:
      name: "Action: Air Quality Alert"
      description: Run when the general air quality index becomes bad.
      default: []
      selector:
        action: {}
    aqi_low_states:
      name: Air Quality Normal States
      description: Action runs when the sensor switches to any of these "clean" states.
      default:
        - "good"
        - "fair"
      selector:
        select:
          multiple: true
          options:
            - "good"
            - "fair"
            - "moderate"
            - "poor"
            - "very_poor"
            - "extremely_poor"
            - "unknown"
    action_aqi_low:
      name: "Action: Air Quality Normal"
      description: Run when the general air quality index becomes good again.
      default: []
      selector:
        action: {}

    # Temperature Settings
    temp_sensor:
      name: Temperature Sensor
      description: Select the temperature sensor entity.
      default: []
      selector:
        entity:
          filter:
            - device_class: temperature
    temp_high_threshold:
      name: High Temperature Threshold
      description: Trigger when temperature goes ABOVE this value.
      default: 26
      selector:
        number:
          min: -20
          max: 50
    action_temp_high:
      name: "Action: High Temperature"
      description: Run when temperature is above threshold.
      default: []
      selector:
        action: {}
    temp_low_threshold:
      name: Low Temperature Threshold
      description: Trigger when temperature goes BELOW this value.
      default: 18
      selector:
        number:
          min: -20
          max: 50
    action_temp_low:
      name: "Action: Low Temperature"
      description: Run when temperature is below threshold.
      default: []
      selector:
        action: {}

    # Humidity Settings
    humidity_sensor:
      name: Humidity Sensor
      description: Select the humidity sensor entity.
      default: []
      selector:
        entity:
          filter:
            - device_class: humidity
    humidity_high_threshold:
      name: High Humidity Threshold
      description: Trigger when humidity goes ABOVE this value (%).
      default: 70
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    action_humidity_high:
      name: "Action: High Humidity"
      description: Run when humidity is high.
      default: []
      selector:
        action: {}
    humidity_low_threshold:
      name: Low Humidity Threshold
      description: Trigger when humidity goes BELOW this value (%).
      default: 30
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    action_humidity_low:
      name: "Action: Low Humidity"
      description: Run when humidity is low.
      default: []
      selector:
        action: {}

mode: parallel
max_exceeded: silent

trigger_variables:
  co2_high_threshold_input: !input co2_high_threshold
  co2_low_threshold_input: !input co2_low_threshold
  pm25_high_threshold_input: !input pm25_high_threshold
  pm25_low_threshold_input: !input pm25_low_threshold
  aqi_trigger_states_input: !input aqi_trigger_states
  aqi_low_states_input: !input aqi_low_states
  stabilization_time_input: !input stabilization_time
  temp_high_threshold_input: !input temp_high_threshold
  temp_low_threshold_input: !input temp_low_threshold
  humidity_high_threshold_input: !input humidity_high_threshold
  humidity_low_threshold_input: !input humidity_low_threshold

triggers:
  - trigger: numeric_state
    entity_id: !input co2_sensor
    above: !input co2_high_threshold
    for:
      seconds: !input stabilization_time
    id: co2_high
  - trigger: numeric_state
    entity_id: !input co2_sensor
    below: !input co2_low_threshold
    for:
      seconds: !input stabilization_time
    id: co2_low
  - trigger: numeric_state
    entity_id: !input pm25_sensor
    above: !input pm25_high_threshold
    for:
      seconds: !input stabilization_time
    id: pm25_high
  - trigger: numeric_state
    entity_id: !input pm25_sensor
    below: !input pm25_low_threshold
    for:
      seconds: !input stabilization_time
    id: pm25_low
  - trigger: state
    entity_id: !input aqi_sensor
    to: !input aqi_trigger_states
    for:
      seconds: !input stabilization_time
    id: aqi_high
  - trigger: state
    entity_id: !input aqi_sensor
    to: !input aqi_low_states
    for:
      seconds: !input stabilization_time
    id: aqi_low
  - trigger: numeric_state
    entity_id: !input temp_sensor
    above: !input temp_high_threshold
    for:
      seconds: !input stabilization_time
    id: temp_high
  - trigger: numeric_state
    entity_id: !input temp_sensor
    below: !input temp_low_threshold
    for:
      seconds: !input stabilization_time
    id: temp_low
  - trigger: numeric_state
    entity_id: !input humidity_sensor
    above: !input humidity_high_threshold
    for:
      seconds: !input stabilization_time
    id: humidity_high
  - trigger: numeric_state
    entity_id: !input humidity_sensor
    below: !input humidity_low_threshold
    for:
      seconds: !input stabilization_time
    id: humidity_low

actions:
  - choose:
      - conditions:
          - condition: trigger
            id: co2_high
          - condition: template
            value_template: >-
              {{ trigger.from_state.state not in ['unavailable', 'unknown', 'none'] and
                 (trigger.from_state.state | float(0)) <= (co2_high_threshold_input | float) }}
        sequence: !input action_co2_high
      - conditions:
          - condition: trigger
            id: co2_low
          - condition: template
            value_template: >-
              {{ trigger.from_state.state not in ['unavailable', 'unknown', 'none'] and
                 (trigger.from_state.state | float(5000)) >= (co2_low_threshold_input | float) }}
        sequence: !input action_co2_low
      - conditions:
          - condition: trigger
            id: pm25_high
          - condition: template
            value_template: >-
              {{ trigger.from_state.state not in ['unavailable', 'unknown', 'none'] and
                 (trigger.from_state.state | float(0)) <= (pm25_high_threshold_input | float) }}
        sequence: !input action_pm25_high
      - conditions:
          - condition: trigger
            id: pm25_low
          - condition: template
            value_template: >-
              {{ trigger.from_state.state not in ['unavailable', 'unknown', 'none'] and
                 (trigger.from_state.state | float(1000)) >= (pm25_low_threshold_input | float) }}
        sequence: !input action_pm25_low
      - conditions:
          - condition: trigger
            id: aqi_high
          - condition: template
            value_template: "{{ trigger.from_state.state not in ['unavailable', 'unknown', 'none'] }}"
        sequence: !input action_aqi_high
      - conditions:
          - condition: trigger
            id: aqi_low
          - condition: template
            value_template: "{{ trigger.from_state.state not in ['unavailable', 'unknown', 'none'] }}"
        sequence: !input action_aqi_low
      - conditions:
          - condition: trigger
            id: temp_high
          - condition: template
            value_template: >-
              {{ trigger.from_state.state not in ['unavailable', 'unknown', 'none'] and
                 (trigger.from_state.state | float(0)) <= (temp_high_threshold_input | float) }}
        sequence: !input action_temp_high
      - conditions:
          - condition: trigger
            id: temp_low
          - condition: template
            value_template: >-
              {{ trigger.from_state.state not in ['unavailable', 'unknown', 'none'] and
                 (trigger.from_state.state | float(100)) >= (temp_low_threshold_input | float) }}
        sequence: !input action_temp_low
      - conditions:
          - condition: trigger
            id: humidity_high
          - condition: template
            value_template: >-
              {{ trigger.from_state.state not in ['unavailable', 'unknown', 'none'] and
                 (trigger.from_state.state | float(0)) <= (humidity_high_threshold_input | float) }}
        sequence: !input action_humidity_high
      - conditions:
          - condition: trigger
            id: humidity_low
          - condition: template
            value_template: >-
              {{ trigger.from_state.state not in ['unavailable', 'unknown', 'none'] and
                 (trigger.from_state.state | float(100)) >= (humidity_low_threshold_input | float) }}
        sequence: !input action_humidity_low
